name: Project item
description: Create a new project item in our backlog
title: "Project Item: "
labels: [ "project" ]
projects: [ "frigvid/1" ]
body:
   -  type: markdown
      attributes:
         value: |
            ## Before you start
            
            Please search our [existing project items](https://github.com/frigvid/app2000-gruppe11/issues?q=label%3Aproject) and open [our backlog](https://github.com/users/frigvid/projects/1) and verify that there isn't an existing item already. Thank you.
            
            ---
   -  type: input
      id: body
      attributes:
         label: Item Body Content
         description: This is the content of the issue, the "body," if you will.
         placeholder: Describe item here.
      validations:
         required: false
